import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/main/Navbar";

const inter = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: "Mahtab's Portfolio",
  description: "Generated by Mahtab",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#030014] overflow-y-scroll overflow-x-hidden text-white`}>
        <div>
        <Navbar/>
        </div>
        {children}
        </body>
    </html>
  );
}
